[package]
name = "rust-dotshix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.12"

[[bin]]
name = "step0_repl"
path = "src/step0_repl.rs"
